### ISSUE TITLE
Make atlas-tracking-js work within iframe

### ISSUE THREAD

**Issue by vanceyen** [Nikkei/atlas-tracking-js#43]
I provide some iframe for other website to embedded. And I want to track some basic behavior within this iframe. However, the current atlas-tracking-js will try to access the properties of the parent frame hence it violates the cross origin policy of the browsers....Is it possible to provide a way such that I can use the atlas-tracking-js within iframe ?

Thanks.

Vance

**Comment by vanceyen** [comment]
Hi atlas team, thanks for submitting the [PR](https://github.com/Nikkei/atlas-tracking-js/pull/45) for this issue. Now the PR has been merged, could you kindly provide some sudo codes as how to correctly set the targetWindow ?

We tried to figure out ourselves but it doesn't work...

Thanks for your help

**Comment by komlow** [comment]
@vanceyen 
You should add `targetWindow` field your config script(`c2p.js`).
Example configuration is [here](https://github.com/Nikkei/atlas-tracking-js/blob/master/dist/c2p.js#L16).

**Comment by vanceyen** [comment]
@komlow Thanks a lot !!! Also I am wondering, do you have timeline regarding when you will generate a new build that has this PR ? Thanks again !

**Comment by oli** [comment]
@komlow Thanks for deploying this fix! I believe historically the Atlas team have built and shared `atj.min.js` with ScoutAsia when there were changes. Is it possible to request a new build, or should we do something else? よろしくお願いします！

**Comment by hjmsano** [comment]
@oli I believe that we already solved this and the latest ATJ has been built & provided.
@komlow Could you mark this ticket as solved?

**Comment by oli** [comment]
@hjmsano Thanks for your assistance here! You’re completely right.
@komlow Apologies for my confusion.
