### ISSUE TITLE
Hit 403

### ISSUE THREAD

**Issue by tinghweetan** [Nikkei/atlas-tracking-js#59]
We were trying to send a request over to atlas to do click tracking on our _alerts_newssearch_, however, there is a scenario that hits Status Code 403 consistently.

Status Code 403 for this Request URL [here](https://atlas-endpoint-staging.scout.asia/ATJ-2.14.2/1626331575641/qdscLmLPRnl/1/ingest?k=885cfd611594f1cb21ecd50b741a9f55a68fc4d8&a=click&c=link&g=https%3A%2F%2Fpreview.scout.asia%2F&r=&i=&u=3B850B4A-A199-40DD-837C-BAAB05D79EF4&aqe=%&d=%7B%22user%w%22external_ids%w%7D%ucustom_object%w%22organisation_name%yTing%xorganisation_status%yPROSPECT%xoriginal_userguid%y3B850B4A-A199-40DD-837C-BAAB05D79EF4%xaffiliateUserId%vnull%uaffiliateUserLevel%vnull%uin_widget%vfalse%uwidget_origin%vnull%uwidget_data%w%22category%vnull%utheme%vnull%7D%7D%utimezone%v8%utimestamp%y2021-07-15T06%3A46%3A15.642Z%xviewport_height%v969%uviewport_width%v1162%uscreen_height%v1080%uscreen_width%v2560%ulayout%yunknown%zcontext%w%22root_id%yqdscLmLPRnlPIduQUp1lRj04MQWuCuizmePD4SEKMXy%xproduct_family%yscoutasia-v2%xproduct%yscoutasia-web-v2%xapp_version%y1.0.0%xpage_title%y%xpage_num%v1%ucampaign%w%22name%y%xsource%y%xmedium%y%xterm%y%xcontent%y%zcustom_object%w%22content%w%22asset_type%ystory%22%7D%7D%ufunnel%w%7D%uvisibility%yvisible%xnavigation_timing%w%22unload%v0%uredirect%v0%udns%v0%utcp%v0%urequest%v93%uresponse%v1%udom%v185%udomContent%v1%uonload%v1%uuntilResponseComplete%v323%uuntilDomComplete%v519%7D%unavigation_type%w%22type%v0%uredirectCount%v0%7D%uaction%w%22name%ymy-alerts-my_alerts%xlocation%ymy-alerts-my_alerts%xdestination%yhttps%3A%2F%2Fpreview.scout.asia%2Fsearch%2Fnews%3Fguid%3D6BCA8DF0-AF9B-4DF5-AD61-AE4404A64A29%xtag%ya%xclass%yjss414%20jss499%20jss470%20jss471%xtext%yChemicals%xdataset%w%22trackable%ymy-alerts-my_alerts%xtrackableUiElement%yalerts_newssearch%xtrackableUiElementGroup%ymy_alerts%xtrackableUiElementDetails%y%5C%226BCA8DF0-AF9B-4DF5-AD61-AE4404A64A29%5C%22%xtrackableObjectName%ynewssearch%xtrackableObjectDetails%y%5C%226BCA8DF0-AF9B-4DF5-AD61-AE4404A64A29%5C%22%22%t%7D)
These are the values we sent;
[alert_newssearch_statusCode403.txt](https://github.com/Nikkei/atlas-tracking-js/files/6820944/alert_newssearch_statusCode403.txt)

But it was able to get Status Code 204 when we removed organisation_name and organisation_status.
Status Code 204 for this Request URL [here](https://atlas-endpoint-staging.scout.asia/ATJ-2.14.2/1626330848574/qdscLmLPRnl/1/ingest?k=885cfd611594f1cb21ecd50b741a9f55a68fc4d8&a=click&c=link&g=https%3A%2F%2Fpreview.scout.asia%2F&r=&i=&u=3B850B4A-A199-40DD-837C-BAAB05D79EF4&aqe=%&d=%7B%22user%w%22external_ids%w%7D%ucustom_object%w%22original_userguid%y3B850B4A-A199-40DD-837C-BAAB05D79EF4%xaffiliateUserId%vnull%uaffiliateUserLevel%vnull%uin_widget%vfalse%uwidget_origin%vnull%uwidget_data%w%22category%vnull%utheme%vnull%7D%7D%utimezone%v8%utimestamp%y2021-07-15T06%3A34%3A08.574Z%xviewport_height%v969%uviewport_width%v1429%uscreen_height%v1080%uscreen_width%v2560%ulayout%yunknown%zcontext%w%22root_id%yqdscLmLPRnlngviZFSFL4uOsc4Hb6iawqrbEVKouzJk%xproduct_family%yscoutasia-v2%xproduct%yscoutasia-web-v2%xapp_version%y1.0.0%xpage_title%y%xpage_num%v1%ucampaign%w%22name%y%xsource%y%xmedium%y%xterm%y%xcontent%y%zcustom_object%w%22content%w%22asset_type%ystory%22%7D%7D%ufunnel%w%7D%uvisibility%yvisible%xnavigation_timing%w%22unload%v0%uredirect%v0%udns%v0%utcp%v0%urequest%v188%uresponse%v0%udom%v606%udomContent%v8%uonload%v1%uuntilResponseComplete%v410%uuntilDomComplete%v1051%7D%unavigation_type%w%22type%v0%uredirectCount%v0%7D%uaction%w%22name%ymy-alerts-my_alerts%xlocation%ymy-alerts-my_alerts%xdestination%yhttps%3A%2F%2Fpreview.scout.asia%2Fsearch%2Fnews%3Fguid%3D6BCA8DF0-AF9B-4DF5-AD61-AE4404A64A29%xtag%ya%xclass%yjss207%20jss467%20jss458%20jss459%xtext%yChemicals%xdataset%w%22trackable%ymy-alerts-my_alerts%xtrackableUiElement%yalerts_newssearch%xtrackableUiElementGroup%ymy_alerts%xtrackableUiElementDetails%y%5C%226BCA8DF0-AF9B-4DF5-AD61-AE4404A64A29%5C%22%xtrackableObjectName%ynewssearch%xtrackableObjectDetails%y%5C%226BCA8DF0-AF9B-4DF5-AD61-AE4404A64A29%5C%22%22%t%7D)
These are the values we sent;
[alert_newssearch_statusCode204.txt](https://github.com/Nikkei/atlas-tracking-js/files/6820902/alert_newssearch_statusCode204.txt)

The only difference between the values in the 2 files above is the organisation_name and organisation_status.
![image](https://user-images.githubusercontent.com/82797648/125742557-d2ae3780-ef60-43ba-af5c-9f5a615c7d1a.png)

Then, we checked that we have another tracking implemented on our _alerts_targetlist_ using a similar request that has the organisation_name and organisation_status, and this request works fine. 
Status Code 204 for this Request URL [here](https://atlas-endpoint-staging.scout.asia/ATJ-2.14.2/1626332046496/qdscLmLPRnl/1/ingest?k=885cfd611594f1cb21ecd50b741a9f55a68fc4d8&a=click&c=link&g=https%3A%2F%2Fpreview.scout.asia%2F&r=&i=&u=3B850B4A-A199-40DD-837C-BAAB05D79EF4&aqe=%&d=%7B%22user%w%22external_ids%w%7D%ucustom_object%w%22organisation_name%yTing%xorganisation_status%yPROSPECT%xoriginal_userguid%y3B850B4A-A199-40DD-837C-BAAB05D79EF4%xaffiliateUserId%vnull%uaffiliateUserLevel%vnull%uin_widget%vfalse%uwidget_origin%vnull%uwidget_data%w%22category%vnull%utheme%vnull%7D%7D%utimezone%v8%utimestamp%y2021-07-15T06%3A54%3A06.497Z%xviewport_height%v969%uviewport_width%v1162%uscreen_height%v1080%uscreen_width%v2560%ulayout%yunknown%zcontext%w%22root_id%yqdscLmLPRnlogORxKM9U5dMhv56FI0OcgE0lu0CuuNo%xproduct_family%yscoutasia-v2%xproduct%yscoutasia-web-v2%xapp_version%y1.0.0%xpage_title%yNews%20%7C%20scoutAsia%xpage_num%v1%ucampaign%w%22name%y%xsource%y%xmedium%y%xterm%y%xcontent%y%zcustom_object%w%22content%w%22asset_type%ystory%22%7D%7D%ufunnel%w%7D%uvisibility%yvisible%xnavigation_timing%w%22unload%v0%uredirect%v0%udns%v0%utcp%v0%urequest%v93%uresponse%v1%udom%v185%udomContent%v1%uonload%v1%uuntilResponseComplete%v323%uuntilDomComplete%v519%7D%unavigation_type%w%22type%v0%uredirectCount%v0%7D%uaction%w%22name%ymy-alerts-my_alerts%xlocation%ymy-alerts-my_alerts%xdestination%yhttps%3A%2F%2Fpreview.scout.asia%2Ftarget-lists%2F36305FC0-442B-42A4-9927-C58CFC8B9728%2Fnews%xtag%ya%xclass%yjss414%20jss936%20jss931%20jss932%xtext%y%5BTargetList%5D%20Construction%20%26%20Materials%xdataset%w%22trackable%ymy-alerts-my_alerts%xtrackableUiElement%yalerts_targetlist%xtrackableUiElementGroup%ymy_alerts%xtrackableUiElementDetails%y%5C%2236305FC0-442B-42A4-9927-C58CFC8B9728%5C%22%xtrackableObjectName%ytargetlist%xtrackableObjectDetails%y%5C%2236305FC0-442B-42A4-9927-C58CFC8B9728%5C%22%22%t%7D)
These are the values we sent;
[alerts_targetlist_statusCode204.txt](https://github.com/Nikkei/atlas-tracking-js/files/6820992/alerts_targetlist_statusCode204.txt)

I am not sure why it is hitting 403 on that particular scenario only. 
Can we check why this is happening and how we could make this work?
Thanks!

Ting Hwee

**Comment by hjmsano** [comment]
I'm trying to reproduce the issue but both requests received 204.
It looks Cloudflare is placed in front of Atlas endpoint, perhaps Cloudflare returned 403?
What do you see if you run the same code on other browser & other network?

**Comment by tinghweetan** [comment]
Hi Hajime, we tried on different browsers and the response varies.

It returns 204 on
1. Internet Explorer
2. Firefox

It returns 403 on
1. Chrome
2. Microsoft Edge

Do you have any idea what could be the problem?

**Comment by oli** [comment]
@hjmsano There appear to be issues with `Navigator.sendBeacon()`, ref:[ Large data study: Navigator.sendBeacon() is broken](https://volument.com/blog/sendbeacon-is-broken). Do you think this might be causing the 403 issues @tinghweetan is seeing? Thanks!

**Comment by hjmsano** [comment]
I guess this is caused by the combination of Cloudflare configuration. Let's continue the conversation on company's Slack.
